export const SafeModeIcons = {
  play: "▶️",
  pause: "⏸️",
  loop: "🔁",
  shuffle: "🔀",
  stop: "⏹️",
  skip: "⏩",
  previous: "⏪",
  voldown: "🔉",
  volup: "🔊",
  arrow_next: "➡",
  arrow_previous: "⬅",
  queue: "📋",
  delete: "🗑",
};
